// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wimparnnhujiegubnxaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbXBhcm5uaHVqaWVndWJueGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDU1NDcsImV4cCI6MjA1NzYyMTU0N30.udsvTSm48xOuvhqut8weKrqssyW8nc3rUvMR7KOIi0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);